apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_DB: "postgresql://revng:cdWVz5vQpcnkBW4QRaPU31YjEuQhZaC3/uRoxJ2ZbVs@postgres-service:5432/django_hello_world"
  DJANGO_DB_USER: "revng"
  DJANGO_DB_PASSWORD: "cdWVz5vQpcnkBW4QRaPU31YjEuQhZaC3/uRoxJ2ZbVs"